// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVcVqNC5LwAV8Xn8BruKvvEyLqlI8Gni8',
    appId: '1:38102823585:web:6ea386178d7f409e9df6e0',
    messagingSenderId: '38102823585',
    projectId: 'flutter-todo-web-305fb',
    authDomain: 'flutter-todo-web-305fb.firebaseapp.com',
    storageBucket: 'flutter-todo-web-305fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVcVqNC5LwAV8Xn8BruKvvEyLqlI8Gni8',
    appId: '1:38102823585:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '38102823585',
    projectId: 'flutter-todo-web-305fb',
    storageBucket: 'flutter-todo-web-305fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.flutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVcVqNC5LwAV8Xn8BruKvvEyLqlI8Gni8',
    appId: '1:38102823585:web:6ea386178d7f409e9df6e0',
    messagingSenderId: '38102823585',
    projectId: 'flutter-todo-web-305fb',
    authDomain: 'flutter-todo-web-305fb.firebaseapp.com',
    storageBucket: 'flutter-todo-web-305fb.firebasestorage.app',
  );
}
