name: Flutter CI

on:
  pull_request:
    branches: [main, staging, dev]
  push:
    branches: [dev]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
      - run: flutter pub get
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
      - name: Install Linux dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
      - name: Install Xvfb
        run: sudo apt-get install -y xvfb
      - run: flutter pub get
      - run: |
          if [ -d "test" ]; then
            flutter test
          else
            echo "No tests found, skipping..."
          fi
      - run: |
          if [ -d "integration_test" ]; then
            xvfb-run -s '-screen 0 1024x768x24' flutter test integration_test -d linux
          else
            echo "No integration tests found, skipping..."
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: flutter build web
